### ISSUE TITLE
Invalid model event callback

### ISSUE THREAD

**Issue by germs2611** [tattersoftware/codeigniter4-audits#12]
Am getting the below snippet error when trying to insert:
![image](https://user-images.githubusercontent.com/73079191/127051332-260a20a7-468e-45cc-b49d-523921edc2a6.png)

**Comment by MGatner** [comment]
Sounds like you didn't include the trait on your model:
```php
use Tatter\Audits\Traits\AuditsTrait;

class MyModel extends Model
{
	use AuditsTrait;
```

**Comment by germs2611** [comment]
![image](https://user-images.githubusercontent.com/73079191/127052337-a1532a88-8c45-432a-9093-63b1e935588f.png)

**Comment by germs2611** [comment]
Oh ok I see the error Tatter and Audits suppose to start with capital letters. Working now.

Thanks,
